spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${RESEND_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.schoolmanagement: DEBUG
    org.hibernate.SQL: DEBUG
app:
  super-admin:
    first-name: Super
    last-name: Admin
    email: ${SUPER_ADMIN_EMAIL:superadmin@schoolms.com}
    password: ${SUPER_ADMIN_PASSWORD:SuperAdmin@123}