spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 60000
      max-lifetime: 600000

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${RESEND_API_KEY:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

app:
  super-admin:
    email: ${SUPER_ADMIN_EMAIL}
    password: ${SUPER_ADMIN_PASSWORD}
    first-name: ${SUPER_ADMIN_FNAME}
    last-name: ${SUPER_ADMIN_LNAME}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiry: 900000
    refresh-token-expiry: 604800000
  mail:
    from: ${MAIL_FROM:noreply@schoolms.com}
  resend:
    api-key: ${RESEND_API_KEY:}

logging:
  level:
    root: INFO
    com.schoolmanagement: INFO
    org.hibernate.SQL: WARN